### ISSUE TITLE
IEC XML example with two languages document

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iec#41]
To generate the IEC multi-languages document in PDF ((https://github.com/metanorma/mn-native-pdf/issues/109) I need the XML example that contains bibdata, boilerplate, preface, section, etc. on a few languages.
Or I need to know the structure of such XML.

**Comment by opoudjis** [comment]
@Intelligent2013 Talk to @ronaldtse about this, we discussed this yesterday.

**Comment by ronaldtse** [comment]
@Intelligent2013 we will have two separate XML files that are identical in structure. Each element in the second document will link to the first document. This way we can ensure both documents are aligned.

There are two kinds of layouts:
* side by side (e.g. two languages every clause/list item are side by side)
* front and back (e.g. a simple concatenation of two documents, where language 1 goes first, then language 2, including the cover/closing pages).

**Comment by opoudjis** [comment]
I have not worked through all the ideas behind this, but I imaging there will be a master document and a slave document. The IDs in the slave document will need to reference IDs in the master document, possibly even including replicating each anchor down to the paragraph level. There will need to be overrides in the master document, to have its content take over the two columns for a particular item.

Make no mistake: this is a massive project, and anything you implement is going to be after I've implemented it. This is many months away.

**Comment by ronaldtse** [comment]
The challenge is when the paired documents have different structures (e.g. markup errors with clauses). We need to detect the errors and throw out the stitching process.

**Comment by opoudjis** [comment]
@Intelligent2013 @ronaldtse We have implemented this in BIPM; is this still a live issue for IEC? If so, you'll need to specify what further is needed.

Side by side is a nightmare of course, because of the difficulties in alignment, and the constant jumping between one and two columns for any figures or examples. If we can avoid doing this, we should.

**Comment by ronaldtse** [comment]
Yes this is a live issue. We need a mechanism to create PDFs in the format described in metanorma/mn-native-pdf#109. There is no need for Word output here.

**Comment by opoudjis** [comment]
Surely this has now been addressed by bilingual collections, as in BIPM? 

https://www.itu.int/en/ITU-D/Technology/Documents/Events2016/CI_Training_ARB_Tunis_April16/Session8/IEC_61000-4-3_2010.pdf is English text followed by French text, so it's the same as the BIPM brochure. The other docs are the same. Therefore there is nothing for *me* to do here: the required XML structure is already in place. 

We don't have a sample document, because of IEC copyright; I assume I can merely concatenate the English and French Rice documents into a collection.

When I do that, this issue is done. Right?

**Comment by ronaldtse** [comment]
Yes this is correct. @Intelligent2013 the action stated by @opoudjis is okay right?

**Comment by Intelligent2013** [comment]
@ronaldtse it's ok for me.

**Comment by opoudjis** [comment]
There are some errors in i18n revealed here, but I think the essentials are in place; the bilingual documents are not currently being split properly either, but that can be left for a later ticket. For now, here is your example:

[bilingual-brochure.zip](https://github.com/metanorma/metanorma-iec/files/5696272/bilingual-brochure.zip)
