### ISSUE TITLE
Introduce data for circulation cover page

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iec#48]
To generate the IEC pre-publication cover pages in PDF (https://github.com/metanorma/mn-native-pdf/issues/120, https://github.com/metanorma/mn-native-pdf/issues/121) we need to have there data in the XML:

- the data 104/864/FDIS, 90/387/CDV (see examples in issues above)
- ~~Closing date for voting~~ (done in metanorma/metanorma-iso#341)
- Indication when we should place 'IEC SC' and when 'IEC TC' information
- Secretary
- Of interest to the following committees
- ~~Proposed horizontal standard~~ (done https://github.com/metanorma/metanorma-iec/issues/46)
- ~Functions concerned (EMC, Environment, Quality assurance, Safety)~ (done https://github.com/metanorma/metanorma-iec/issues/45)
- ~Indication of 'Submitted for CENELEC parallel voting' (true, false)~ and Attention text (CENELEC is cen-processing: https://github.com/metanorma/metanorma-iec/issues/47)
- other texts ('This document is a draft distributed for approval....', 'Chicago (USA) on April 9th...', 'This document is also of interest for ISO/ TC114/ WG1 Requirements for Watch batteries')
- Note from TC/SC officers
- ~~Proposed stability date~~ (see below https://github.com/metanorma/metanorma-iec/issues/48#issuecomment-619353624)
- Copyright text

This issue is to add these information.

**Comment by opoudjis** [comment]
Of these, some data is  already available:

* "Closing date for voting" is `//bibdata/date[@type = 'vote-closed']`, introduced in https://github.com/metanorma/metanorma-iso/issues/341
* The stability text is `//bibdata/date[@type = 'unchanged']`

**Comment by opoudjis** [comment]
@ronaldtse Obviously, I must get hold of this coverpage for DOC and HTML. Kindly provide it.

**Comment by ronaldtse** [comment]
@opoudjis please see: https://github.com/metanorma/metanorma-iec/issues/49

**Comment by ronaldtse** [comment]
> "Closing date for voting" is //bibdata/date[@type = 'vote-closed'], introduced in metanorma/metanorma-iso#341

This is a mistake -- the correct attributes introduced are `vote-started` and `vote-ended`.

**Comment by opoudjis** [comment]
Already done:

- Closing date for voting: `//bibdata/date[@type = 'vote-ended']`
- Proposed horizontal standard: `//bibdata/ext/horizontal`
- Functions concerned (EMC, Environment, Quality assurance, Safety): `//bibdata/ext/function`
- Indication of 'Submitted for CENELEC parallel voting' (true, false): `//bibdata/ext/cen-processing` 
- Proposed stability date: `//bibdata/date[@type = 'unchanged']`

To do:

- the data 104/864/FDIS, 90/387/CDV (see examples in issues above)
- Indication when we should place 'IEC SC' and when 'IEC TC' information
- Secretary
- Of interest to the following committees
- Indication of CENELEC Attention text
- other texts ('This document is a draft distributed for approval....', 'Chicago (USA) on April 9th...', 'This document is also of interest for ISO/ TC114/ WG1 Requirements for Watch batteries')
- Note from TC/SC officers
- Copyright text

**Comment by opoudjis** [comment]
Boilerplate remains to be done

**Comment by opoudjis** [comment]
Of the remainder:

I am assuming that the cover page is English only, and I am replicating English-language boilerplate to the French boilerplate file.

This boilerplate appears in the coverpage which *replaces* the publication cover page (and inside cover page) for unpublished drafts. 

Therefore, the copyright statement shall appear in //copyright-statement, replacing in draft documents the published document copyright statement that you have been seeing until now.

The draft warning (which is different for CD and FDIS), "This document is a draft...", is inserted in //license-statement; it replaces the text we made up, modelled after ISO, which it turns out is not used by IEC at all.

The CENELEC Attention text is inserted in //feedback-statement, with id boilerplate-cenelec-attention; it replaces the extensive text which appears in published documents in the inside cover.

**Comment by opoudjis** [comment]
Have updated rspec so it uses live boilerplate file and runs Liquid on it, rather than try and fake it with regexes

**Comment by opoudjis** [comment]
[coverpage.zip](https://github.com/metanorma/metanorma-iec/files/5750501/coverpage.zip)
